export const siteConfig = {
  name: "claudemaxing.shop",
  brandMark: "CLAUDEMAXING",
  tagline: "Claude-powered API access",
  description: "Managed Claude-powered API access with dedicated monthly capacity allocations.",
  email: "support@claudemaxing.shop",
  emailSecondary: "guntekgtofficial@gmail.com",
  phone: "+91 96646 50235",
  whatsapp: "+91 96646 50235",
  address: "India",
  gstin: process.env.MERCHANT_GSTIN || "",
  pan: process.env.MERCHANT_PAN || "",
  appUrl: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  disclaimer:
    "claudemaxing.shop provides managed Claude-powered API access. We are an independent service and not Anthropic PBC or an official consumer subscription storefront.",
  refundPolicySummary:
    "All purchases are non-refundable and non-cancellable after successful payment, except where a refund is required by applicable law or where a payment is charged but the service is not delivered according to the merchant's stated fulfilment terms.",
  plans: [
    {
      id: "plan_5x_access",
      name: "5X Access",
      slug: "5x-access",
      price: parseInt(process.env.PLAN_MAX_5X_PRICE || "999", 10),
      currency: "INR",
      billingPeriod: "month",
      multiplier: "5X",
      description: "For regular users who need substantially more usage than standard access.",
      defaultMaxCustomers: 10,
      features: [
        "5X capacity allocation",
        "Managed Claude-powered access",
        "Fast delivery via Email or WhatsApp",
        "30-day access validity",
        "Support included",
      ],
      cta: "Get 5X",
    },
    {
      id: "plan_20x_access",
      name: "20X Access",
      slug: "20x-access",
      price: parseInt(process.env.PLAN_MAX_20X_PRICE || "1999", 10),
      currency: "INR",
      billingPeriod: "month",
      multiplier: "20X",
      description: "For heavier daily use and demanding professional workflows.",
      defaultMaxCustomers: 5,
      features: [
        "20X capacity allocation",
        "High-throughput Claude-powered access",
        "Fast delivery via Email or WhatsApp",
        "30-day access validity",
        "Support included",
      ],
      cta: "Get 20X",
    },
  ],
};
