export const siteConfig = {
  name: process.env.MERCHANT_NAME || "Krypton Subscriptions",
  brandMark: "KRYPTON",
  description: "Secure, account-based storefront for authorized Claude subscription plans.",
  email: process.env.MERCHANT_EMAIL || "support@kryptoncloud.in",
  phone: process.env.MERCHANT_PHONE || "+91 98765 43210",
  address: process.env.MERCHANT_ADDRESS || "Bengaluru, Karnataka, India",
  gstin: process.env.MERCHANT_GSTIN || "",
  pan: process.env.MERCHANT_PAN || "",
  appUrl: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  disclaimer:
    "This storefront is an independent authorized service provider facilitating Claude subscriptions. We are not Anthropic PBC, and this store is not Anthropic itself.",
  plans: [
    {
      id: "plan_claude_max_5x",
      name: "Claude Max 5x",
      slug: "claude-max-5x",
      price: parseInt(process.env.PLAN_MAX_5X_PRICE || "999", 10),
      currency: "INR",
      billingPeriod: "month",
      multiplier: "5x",
      description: "For regular users who need substantially more usage than the standard plan.",
      features: [
        "5x usage tier",
        "Monthly subscription",
        "Account-based purchase",
        "Secure payment",
        "Support included",
      ],
      cta: "Get 5x",
    },
    {
      id: "plan_claude_max_20x",
      name: "Claude Max 20x",
      slug: "claude-max-20x",
      price: parseInt(process.env.PLAN_MAX_20X_PRICE || "1999", 10),
      currency: "INR",
      billingPeriod: "month",
      multiplier: "20x",
      description: "For heavier daily use and demanding workflows.",
      features: [
        "20x usage tier",
        "Monthly subscription",
        "Account-based purchase",
        "Secure payment",
        "Support included",
      ],
      cta: "Get 20x",
    },
  ],
};
